ERRORS:
test_ln_calc (sample.google_calc.PyGoogleCalc)
Traceback (most recent call last):
  File "C:\Install\Work\GoogleCalculator\sample\google_calc.py", line 72, in tearDown
    self.driver.get_screenshot_as_file(outPngFile)
  File "C:\Python34\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 896, in get_screenshot_as_file
    png = self.get_screenshot_as_png()
  File "C:\Python34\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 928, in get_screenshot_as_png
    return base64.b64decode(self.get_screenshot_as_base64().encode('ascii'))
  File "C:\Python34\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 938, in get_screenshot_as_base64
    return self.execute(Command.SCREENSHOT)['value']
  File "C:\Python34\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "C:\Python34\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot get automation extension
from unknown error: page could not be found: chrome-extension://aapnijgdinlhnhlmodcfapnahmbfebeb/_generated_background_page.html
  (Session info: chrome=61.0.3163.100)
  (Driver info: chromedriver=2.27.440174 (e97a722caafc2d3a8b807ee115bfb307f7d2cfd9),platform=Windows NT 10.0.15063 x86_64)


test_long_calc (sample.google_calc.PyGoogleCalc)
Traceback (most recent call last):
  File "C:\Install\Work\GoogleCalculator\sample\google_calc.py", line 72, in tearDown
    self.driver.get_screenshot_as_file(outPngFile)
  File "C:\Python34\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 896, in get_screenshot_as_file
    png = self.get_screenshot_as_png()
  File "C:\Python34\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 928, in get_screenshot_as_png
    return base64.b64decode(self.get_screenshot_as_base64().encode('ascii'))
  File "C:\Python34\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 938, in get_screenshot_as_base64
    return self.execute(Command.SCREENSHOT)['value']
  File "C:\Python34\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "C:\Python34\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot get automation extension
from unknown error: page could not be found: chrome-extension://aapnijgdinlhnhlmodcfapnahmbfebeb/_generated_background_page.html
  (Session info: chrome=61.0.3163.100)
  (Driver info: chromedriver=2.27.440174 (e97a722caafc2d3a8b807ee115bfb307f7d2cfd9),platform=Windows NT 10.0.15063 x86_64)


test_multy_calc (sample.google_calc.PyGoogleCalc)
Traceback (most recent call last):
  File "C:\Install\Work\GoogleCalculator\sample\google_calc.py", line 72, in tearDown
    self.driver.get_screenshot_as_file(outPngFile)
  File "C:\Python34\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 896, in get_screenshot_as_file
    png = self.get_screenshot_as_png()
  File "C:\Python34\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 928, in get_screenshot_as_png
    return base64.b64decode(self.get_screenshot_as_base64().encode('ascii'))
  File "C:\Python34\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 938, in get_screenshot_as_base64
    return self.execute(Command.SCREENSHOT)['value']
  File "C:\Python34\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "C:\Python34\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot get automation extension
from unknown error: page could not be found: chrome-extension://aapnijgdinlhnhlmodcfapnahmbfebeb/_generated_background_page.html
  (Session info: chrome=61.0.3163.100)
  (Driver info: chromedriver=2.27.440174 (e97a722caafc2d3a8b807ee115bfb307f7d2cfd9),platform=Windows NT 10.0.15063 x86_64)


test_plus_calc (sample.google_calc.PyGoogleCalc)
Traceback (most recent call last):
  File "C:\Install\Work\GoogleCalculator\sample\google_calc.py", line 72, in tearDown
    self.driver.get_screenshot_as_file(outPngFile)
  File "C:\Python34\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 896, in get_screenshot_as_file
    png = self.get_screenshot_as_png()
  File "C:\Python34\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 928, in get_screenshot_as_png
    return base64.b64decode(self.get_screenshot_as_base64().encode('ascii'))
  File "C:\Python34\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 938, in get_screenshot_as_base64
    return self.execute(Command.SCREENSHOT)['value']
  File "C:\Python34\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "C:\Python34\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot get automation extension
from unknown error: page could not be found: chrome-extension://aapnijgdinlhnhlmodcfapnahmbfebeb/_generated_background_page.html
  (Session info: chrome=61.0.3163.100)
  (Driver info: chromedriver=2.27.440174 (e97a722caafc2d3a8b807ee115bfb307f7d2cfd9),platform=Windows NT 10.0.15063 x86_64)


